export const COLUMNS = 'abcdefgh'.split('');

export const chessboardDefaultProps = {
  animationDuration: 300,
  areArrowsAllowed: true,
  arePremovesAllowed: false,
  boardOrientation: 'white',
  boardWidth: 560,
  clearPremovesOnRightClick: true,
  customArrows: [],
  customArrowColor: 'rgb(255,170,0)',
  customBoardStyle: {},
  customDarkSquareStyle: { backgroundColor: '#B58863' },
  customDndBackend: undefined,
  customDndBackendOptions: undefined,
  customLightSquareStyle: { backgroundColor: '#F0D9B5' },
  customPieces: {},
  customPremoveDarkSquareStyle: { backgroundColor: '#A42323' },
  customPremoveLightSquareStyle: { backgroundColor: '#BD2828' },
  customSquareStyles: {},
  id: 0,
  getPositionObject: () => {},
  onMouseOutSquare: () => {},
  onMouseOverSquare: () => {},
  onPieceClick: () => {},
  onSquareClick: () => {},
  onSquareRightClick: () => {},
  position: 'start',
  showBoardNotation: true,
  // showSparePieces: false,
  snapToCursor: true
};
